/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u        /*!<@brief Input Buffer Enable: Enables */
#define PORT5_PCR_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT1_8 (coord A1), P1_8/J9[32]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                                        /* @} */

/*! @name PORT1_9 (coord B1), P1_9/J9[30]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                                        /* @} */

/*! @name PORT1_2 (coord C4), ARD_D6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D6_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D6_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D6_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D6_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D6_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D6_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORT0_14 (coord E11), ARD_A2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_A2_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_A2_GPIO_PIN 14U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_A2_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_A2_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_A2_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_A2_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT0_22 (coord B8), ARD_A3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_A3_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_A3_GPIO_PIN 22U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_A3_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_A3_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_A3_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_A3_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT0_15 (coord G13), ARD_A4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_A4_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_A4_GPIO_PIN 15U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_A4_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_A4_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_A4_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_A4_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT0_23 (coord B7), ARD_A5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_A5_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_A5_GPIO_PIN 23U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_A5_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_A5_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_A5_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_A5_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT4_3 (coord U1), ARD_D0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D0_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D0_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D0_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D0_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D0_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D0_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORT4_2 (coord T1), ARD_D1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D1_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D1_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D1_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D1_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D1_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D1_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORT0_29 (coord F8), ARD_D2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D2_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D2_GPIO_PIN 29U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D2_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D2_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D2_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D2_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT1_23 (coord M4), ARD_D3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D3_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D3_GPIO_PIN 23U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D3_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D3_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D3_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D3_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT0_30 (coord E7), ARD_D4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D4_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D4_GPIO_PIN 30U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D4_GPIO_PIN_MASK (1U << 30U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D4_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D4_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D4_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT1_21 (coord L5), ARD_D5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D5_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D5_GPIO_PIN 21U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D5_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D5_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D5_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D5_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT0_31 (coord D7), ARD_D7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D7_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D7_GPIO_PIN 31U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D7_GPIO_PIN_MASK (1U << 31U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D7_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D7_PIN 31U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D7_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT0_28 (coord E8), ARD_D8
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D8_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D8_GPIO_PIN 28U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D8_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D8_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D8_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D8_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT0_10 (coord B12), ARD_D9
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D9_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D9_GPIO_PIN 10U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D9_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D9_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D9_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D9_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT0_27 (coord E10), ARD_D10
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D10_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D10_GPIO_PIN 27U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D10_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D10_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D10_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D10_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PORT0_24 (coord B6), ARD_D11
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D11_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D11_GPIO_PIN 24U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D11_GPIO_PIN_MASK (1U << 24U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D11_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D11_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D11_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PORT0_26 (coord F10), ARD_D12
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D12_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D12_GPIO_PIN 26U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D12_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D12_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D12_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D12_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PORT0_25 (coord A6), ARD_D13
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D13_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D13_GPIO_PIN 25U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D13_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D13_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D13_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D13_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PORT0_6 (coord C14), P0_6/J23[7]/SW3[3]/SW3[4]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_SW3_GPIO GPIO0               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_SW3_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_SW3_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_SW3_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_SW3_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_SW3_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT4_0 (coord P1), ARD_D18
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D18_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D18_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D18_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D18_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D18_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D18_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT4_1 (coord P2), ARD_D19
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D19_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D19_GPIO_PIN 1U              /*!<@brief GPIO pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D19_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_ARD_D19_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_ARD_D19_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_ARD_D19_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name PORT0_1 (coord A16), P0_1/SWCLK/J23[4]/D16[5]/J22[2]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                                          /* @} */

/*! @name PORT0_0 (coord A17), P0_0/SWDIO/J23[2]/D16[6]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                         /* @} */

/*! @name PORT0_2 (coord B16), P0_2/SWO/J23[6]/D16[4]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSWD_DEBUGPins(void);

/*! @name PORT1_2 (coord C4), ARD_D6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_ARD_D6_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_ARD_D6_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_ARD_D6_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_ARD_D6_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_ARD_D6_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_ARD_D6_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT0_10 (coord B12), ARD_D9
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_ARD_D9_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_ARD_D9_GPIO_PIN 10U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_ARD_D9_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_ARD_D9_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_ARD_D9_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_ARD_D9_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT0_27 (coord E10), ARD_D10
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_ARD_D10_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_ARD_D10_GPIO_PIN 27U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_ARD_D10_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_ARD_D10_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_ARD_D10_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_ARD_D10_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

/*! @name PORT0_6 (coord C14), P0_6/J23[7]/SW3[3]/SW3[4]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW3_GPIO GPIO0               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_SW3_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_SW3_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT0_23 (coord B7), ARD_A5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_ARD_A5_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_ARD_A5_GPIO_PIN 23U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_ARD_A5_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_ARD_A5_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_ARD_A5_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_ARD_A5_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
